#!/usr/bin/env bash
# scripts/cleanup_network.sh
# Interaktives Aufräum-Script für Access-Point / Netzwerk-Konfiguration
# Ziel: Entfernt typische AP-Konfigs (hostapd/dnsmasq/wpa_supplicant overrides, dhcpcd blocks)
# und gibt vor jeder Aktion eine Bestätigung ("durchklicken").
# LICHTE WARNUNG: Führt Aktionen mit root-Rechten aus. Prüfe die angezeigten Befehle
# bevor du sie bestätigst. Das Script legt vor Änderungen Backups an.

set -euo pipefail

need_root() {
  if [[ $EUID -ne 0 ]]; then
    echo "Bitte mit sudo ausführen: sudo bash $0" >&2
    exit 1
  fi
}

confirm() {
  # prompt with default No
  local prompt="$1"
  local reply
  while true; do
    read -rp "$prompt [y/N/q] " reply
    case "${reply,,}" in
      y|yes) return 0 ;;
      n|no|"") return 1 ;;
      q|quit) echo "Abgebrochen."; exit 0 ;;
      *) echo "Bitte 'y' (ja), 'n' (nein) oder 'q' (quit) eingeben." ;;
    esac
  done
}

info() { echo -e "\e[34m[INFO]\e[0m $*"; }
warn() { echo -e "\e[33m[WARN]\e[0m $*"; }
err() { echo -e "\e[31m[ERR]\e[0m $*"; }

# Show likely backup files generated by previous scripts
list_backups() {
  echo "Mögliche Backups (nur Anzeige):"
  ls -1 /etc/dhcpcd.conf*.bak* 2>/dev/null || true
  ls -1 /etc/hostapd/hostapd.conf* 2>/dev/null || true
  ls -1 /etc/dnsmasq.d/krippe_ap.conf* 2>/dev/null || true
  ls -1 /etc/default/hostapd* 2>/dev/null || true
  ls -1 /etc/systemd/system/wpa_supplicant@*.service.d/* 2>/dev/null || true
}

run_cmd() {
  echo "+ $*"
  eval "$@"
}

main() {
  need_root

  echo
  echo "== Interaktives Netzwerk-Aufräum-Skript: Durchklicken jeder Aktion"
  echo "Tipps: 'y' = ausführen, 'n' = überspringen, 'q' = abbrechen"
  echo

  list_backups
  echo

  if confirm "Möchtest du mit dem Aufräumen beginnen?"; then
    info "Beginne Aufräumen..."
  else
    echo "Keine Aktion ausgeführt."; exit 0
  fi

  # 1) Stoppe Dienste (hostapd, dnsmasq, wpa_supplicant@wlan0)
  if confirm "1) Dienste stoppen: hostapd, dnsmasq, wpa_supplicant@wlan0?"; then
    info "Stopping services"
    run_cmd "systemctl stop hostapd || true"
    run_cmd "systemctl stop dnsmasq || true"
    run_cmd "systemctl stop wpa_supplicant@wlan0 || true"
  else
    info "Schritt 1 übersprungen"
  fi

  # 2) Remove AP block from dhcpcd.conf (with backup)
  if [[ -f /etc/dhcpcd.conf ]]; then
    echo "
    Im folgenden wird ein Backup von /etc/dhcpcd.conf erzeugt und dann der Block
    zwischen '# KRIPPE_AP_START' und '# KRIPPE_AP_END' entfernt (sofern vorhanden)."
    if confirm "2) /etc/dhcpcd.conf bereinigen? (Backup wird erstellt)"; then
      local ts
      ts=$(date +%Y%m%d-%H%M%S)
      run_cmd "cp -a /etc/dhcpcd.conf /etc/dhcpcd.conf.bak-${ts}"
      run_cmd "sed -i '/^# KRIPPE_AP_START/,/^# KRIPPE_AP_END/d' /etc/dhcpcd.conf || true"
      info "dhcpcd.conf bereinigt (Backup: /etc/dhcpcd.conf.bak-${ts})"
    else
      info "Schritt 2 übersprungen"
    fi
  else
    warn "/etc/dhcpcd.conf nicht gefunden, Schritt 2 übersprungen"
  fi

  # 3) Remove dnsmasq krippe file
  if confirm "3) /etc/dnsmasq.d/krippe_ap.conf entfernen (falls vorhanden)?"; then
    if [[ -f /etc/dnsmasq.d/krippe_ap.conf ]]; then
      run_cmd "mv -f /etc/dnsmasq.d/krippe_ap.conf /etc/dnsmasq.d/krippe_ap.conf.removed.$(date +%s)"
      info "krippe_ap.conf verschoben"
    else
      info "krippe_ap.conf nicht vorhanden"
    fi
  else
    info "Schritt 3 übersprungen"
  fi

  # 4) Archive or remove hostapd.conf
  if [[ -f /etc/hostapd/hostapd.conf ]]; then
    echo
    echo "4) /etc/hostapd/hostapd.conf wird gesichert und verschoben (nicht gelöscht)."
    if confirm "Weiter?"; then
      run_cmd "cp -a /etc/hostapd/hostapd.conf /etc/hostapd/hostapd.conf.removed.$(date +%s)"
      run_cmd "rm -f /etc/hostapd/hostapd.conf"
      info "hostapd.conf gesichert und entfernt"
    else
      info "Schritt 4 übersprungen"
    fi
  else
    info "Keine hostapd.conf gefunden"
  fi

  # 5) Clean /etc/default/hostapd DAEMON_CONF line
  if [[ -f /etc/default/hostapd ]]; then
    echo
    echo "5) /etc/default/hostapd: Entferne DAEMON_CONF= Zeile (falls vorhanden). Backup wird erstellt."
    if confirm "Weiter?"; then
      run_cmd "cp -a /etc/default/hostapd /etc/default/hostapd.bak.$(date +%s)"
      run_cmd "sed -i '/^DAEMON_CONF=/d' /etc/default/hostapd || true"
      info "/etc/default/hostapd bereinigt"
    else
      info "Schritt 5 übersprungen"
    fi
  fi

  # 6) Remove wpa_supplicant override for wlan0
  if [[ -d /etc/systemd/system/wpa_supplicant@wlan0.service.d ]]; then
    echo
    echo "6) Entferne wpa_supplicant@wlan0 override (erzeugt von Script, falls vorhanden)"
    if confirm "Weiter?"; then
      run_cmd "rm -f /etc/systemd/system/wpa_supplicant@wlan0.service.d/override.conf || true"
      run_cmd "rmdir --ignore-fail-on-non-empty /etc/systemd/system/wpa_supplicant@wlan0.service.d || true"
      run_cmd "systemctl daemon-reload || true"
      info "wpa_supplicant override entfernt"
    else
      info "Schritt 6 übersprungen"
    fi
  else
    info "Kein wpa_supplicant override-Verzeichnis gefunden"
  fi

  # 7) Remove NetworkManager unmanaged.conf (if present)
  if [[ -f /etc/NetworkManager/conf.d/unmanaged.conf ]]; then
    echo
    echo "7) Entferne /etc/NetworkManager/conf.d/unmanaged.conf (wenn von Script gesetzt)"
    if confirm "Weiter?"; then
      run_cmd "mv -f /etc/NetworkManager/conf.d/unmanaged.conf /etc/NetworkManager/conf.d/unmanaged.conf.removed.$(date +%s)"
      run_cmd "systemctl restart NetworkManager || true"
      info "NetworkManager-Konfig entfernt und NM neu gestartet"
    else
      info "Schritt 7 übersprungen"
    fi
  else
    info "Keine NetworkManager unmanaged.conf gefunden"
  fi

  # 8) Restart dhcpcd
  if confirm "8) dhcpcd neu starten (wichtig, damit /etc/dhcpcd.conf wirksam wird)?"; then
    run_cmd "systemctl restart dhcpcd || true"
    info "dhcpcd neu gestartet"
  else
    info "Schritt 8 übersprungen"
  fi

  # 9) Optionally purge hostapd/dnsmasq
  echo
  if confirm "9) hostapd und dnsmasq vollständig deinstallieren (purge)? (Achtung: Pakete werden entfernt)"; then
    run_cmd "apt purge -y hostapd dnsmasq || true"
    run_cmd "apt autoremove -y || true"
    info "hostapd/dnsmasq entfernt"
  else
    info "Schritt 9 übersprungen"
  fi

  # 10) Show status and helpful next commands
  echo
  info "Aufräumvorgang abgeschlossen (Teilschritte ggf. übersprungen). Prüfe den Status mit folgenden Befehlen:"
  echo " sudo ip addr show"
  echo " sudo iw list | sed -n '1,120p'"
  echo " sudo rfkill list"
  echo " sudo systemctl status hostapd dnsmasq wpa_supplicant@wlan0 NetworkManager --no-pager"
  echo
  info "Wenn du jetzt eine frische AP-Konfiguration per NetworkManager willst, führe ggf. ./setup_nm_accesspoint.sh aus."
  echo
  info "Fertig."
}

main "$@"
